const ROOMS=[{id:"brew",name:"Morning Brew",description:"Casual check-ins and conversation"},{id:"engineering",name:"Engineering Hub",description:"Standups, pairing, and delivery work"},{id:"design",name:"Design Studio",description:"Reviews and collaborative ideation"},{id:"focus",name:"Focus Zone",description:"Quiet deep-work sessions"}];
const DEMO_PEOPLE=[{id:"demo-1",name:"Avery",status:"available",room:"engineering",activity:"Reviewing a pull request",demo:true},{id:"demo-2",name:"Jordan",status:"focus",room:"focus",activity:"Focus session",demo:true},{id:"demo-3",name:"Morgan",status:"busy",room:"design",activity:"Design review",demo:true}];
const INTEGRATIONS=[{name:"Slack",href:"https://slack.com/app",detail:"Open workspace"},{name:"Notion",href:"https://www.notion.so",detail:"Open docs"},{name:"GitHub",href:"https://github.com",detail:"Open repositories"},{name:"Jira",href:"https://www.atlassian.com/software/jira",detail:"Open projects"},{name:"Calendar",href:"https://calendar.google.com",detail:"Open schedule"},{name:"Zoom",href:"https://zoom.us",detail:"Open meetings"}];
const clientId=localStorage.getItem("spring-client-id")||crypto.randomUUID();
localStorage.setItem("spring-client-id",clientId);
const settings=JSON.parse(localStorage.getItem("spring-settings")||"{}");
const state={me:{id:clientId,name:settings.name||"You",status:"available",room:null,activity:"Ready to work"},room:"engineering",apiUrl:settings.apiUrl||"",people:[],events:["Welcome to Spring Office. Join a room to begin."],timer:JSON.parse(localStorage.getItem("spring-timer")||'{"kind":"focus","total":1500,"remaining":1500,"running":false,"completedFocus":0,"sessions":0,"breaks":0}'),timerHandle:null,pollHandle:null};
const el=id=>document.getElementById(id);
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()||"ME";
const titleCase=value=>value.charAt(0).toUpperCase()+value.slice(1);
const api=path=>state.apiUrl.replace(/\/$/,"")+path;
const escapeHtml=text=>String(text).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function notify(text){const notice=el("notice");notice.textContent=text;notice.classList.add("show");clearTimeout(notice.timeout);notice.timeout=setTimeout(()=>notice.classList.remove("show"),2800)}
function saveSettings(){localStorage.setItem("spring-settings",JSON.stringify({name:state.me.name,apiUrl:state.apiUrl}))}
function saveTimer(){localStorage.setItem("spring-timer",JSON.stringify(state.timer))}
function addEvent(text){state.events.unshift(text);state.events=state.events.slice(0,4);renderEvents()}
function activePeople(){return state.apiUrl?state.people:[state.me,...DEMO_PEOPLE]}
function renderRooms(){const people=activePeople();el("roomLinks").innerHTML=ROOMS.map(room=>{const count=people.filter(person=>person.room===room.id).length;return `<button class="room-link ${room.id===state.room?"selected":""}" data-room="${room.id}"><span class="dot ${count?"online":""}"></span><span>${room.name}</span><span class="room-count">${count}</span></button>`}).join("");document.querySelectorAll(".room-link").forEach(button=>button.addEventListener("click",()=>{state.room=button.dataset.room;renderOffice()}))}
function statusBadge(person){return `<span class="badge ${person.status}">${person.demo?"Preview ":""}${titleCase(person.status)}</span>`}
function renderStage(){const room=ROOMS.find(item=>item.id===state.room);const occupants=activePeople().filter(person=>person.room===state.room);el("activeRoomTitle").textContent=room.name;el("activeRoomDescription").textContent=room.description;el("joinButton").textContent=state.me.room===state.room?"Leave room":"Join room";let desks=occupants.map(person=>`<div class="desk"><div class="desk-person"><span class="avatar">${initials(person.name)}</span><div><strong>${escapeHtml(person.name)}</strong><span class="person-state ${person.status}"><span class="dot online"></span>${titleCase(person.status)}</span></div></div><div class="desk-foot">${escapeHtml(person.activity||(person.demo?"Preview teammate":"Present in room"))}</div></div>`);while(desks.length<4)desks.push('<div class="desk empty">Open desk<br><span class="tiny">Waiting for a teammate</span></div>');el("deskBoard").innerHTML=desks.join("")}
function renderPresence(){const people=activePeople();const visible=people.filter(person=>person.room);el("peopleList").innerHTML=visible.length?visible.map(person=>`<div class="person"><span class="avatar">${initials(person.name)}</span><div class="person-details"><strong>${escapeHtml(person.name)}</strong><small>${ROOMS.find(room=>room.id===person.room)?.name||"Not in a room"}</small></div>${statusBadge(person)}</div>`).join(""):'<p class="tiny">No one has joined a room yet.</p>';el("onlineCount").textContent=`${state.apiUrl?people.length:1} online`;el("presenceMode").textContent=state.apiUrl?"Live shared presence":"Preview teammates";el("syncState").textContent=state.apiUrl?"Connected online":"Local mode";el("botMode").textContent=state.apiUrl?"API connected":"Local helper"}
function renderEvents(){el("eventLog").innerHTML=state.events.map(event=>`<div class="event"><span class="dot online"></span><span>${escapeHtml(event)}</span></div>`).join("")}
function renderOffice(){renderRooms();renderStage();renderPresence();renderEvents()}
async function toggleJoin(){const joining=state.me.room!==state.room;state.me.room=joining?state.room:null;state.me.activity=joining?"Working in "+ROOMS.find(room=>room.id===state.room).name:"Available";addEvent(joining?`${state.me.name} joined ${ROOMS.find(room=>room.id===state.room).name}.`:`${state.me.name} left the room.`);await sendPresence();renderOffice()}
async function sendPresence(){if(!state.apiUrl)return;try{const response=await fetch(api("/api/presence"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(state.me)});if(!response.ok)throw new Error();const data=await response.json();state.people=data.people||[];renderOffice()}catch(_error){notify("Backend unavailable. Returned to local mode.");state.apiUrl="";saveSettings();renderOffice()}}
async function pollPresence(){if(!state.apiUrl)return;try{const response=await fetch(api("/api/presence"));if(!response.ok)throw new Error();state.people=(await response.json()).people||[];renderOffice()}catch(_error){el("syncState").textContent="Reconnect needed"}}
function startPolling(){clearInterval(state.pollHandle);if(state.apiUrl){sendPresence();state.pollHandle=setInterval(()=>{sendPresence();pollPresence()},10000)}}
function setView(name){document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.id==="view-"+name));document.querySelectorAll(".nav button").forEach(button=>button.classList.toggle("active",button.dataset.view===name));const views={office:["Office","Join a room and see who is working with you."],notes:["Meeting notes","Turn conversation into decisions and follow-ups."],wellness:["Wellness","Build a sustainable focus rhythm."],integrations:["Integrations","Move between the tools your team uses."],bot:["SpringBot","Ask for help and keep work moving."],settings:["Settings","Connect shared services and personalize your office."]};el("viewTitle").textContent=views[name][0];el("viewDescription").textContent=views[name][1]}
function formatTime(seconds){return `${Math.floor(seconds/60).toString().padStart(2,"0")}:${(seconds%60).toString().padStart(2,"0")}`}
function renderTimer(){const timer=state.timer;el("timerDisplay").textContent=formatTime(timer.remaining);el("timerProgress").style.width=`${((timer.total-timer.remaining)/timer.total)*100}%`;el("timerModeLabel").textContent=titleCase(timer.kind);el("timerToggle").textContent=timer.running?"Pause":"Start";document.querySelectorAll(".pill").forEach(pill=>pill.classList.toggle("active",Number(pill.dataset.minutes)*60===timer.total&&pill.dataset.kind===timer.kind));el("focusMinutesMetric").textContent=`${Math.round(timer.completedFocus/60)}m`;el("sessionsMetric").textContent=timer.sessions;el("breaksMetric").textContent=timer.breaks;el("wellnessPrompt").textContent=timer.completedFocus>=7200?"You have logged two hours of focus. Take a recovery break before another session.":timer.sessions?"Strong rhythm. Schedule a break between deep work sessions.":"Start a focus block from the timer to begin tracking your work rhythm.";saveTimer()}
function timerTick(){if(!state.timer.running)return;state.timer.remaining-=1;if(state.timer.remaining<=0){state.timer.remaining=0;state.timer.running=false;if(state.timer.kind==="focus"){state.timer.sessions+=1;state.timer.completedFocus+=state.timer.total;el("timerHint").textContent="Focus complete. Choose the 5m break preset to recharge.";notify("Focus session complete. Time for a break.")}else{state.timer.breaks+=1;el("timerHint").textContent="Break complete. You are ready for your next focus block.";notify("Break complete.")}}renderTimer()}
function setTimerPreset(minutes,kind){state.timer.kind=kind;state.timer.total=minutes*60;state.timer.remaining=state.timer.total;state.timer.running=false;el("timerHint").textContent=kind==="focus"?"A short break will be suggested after your focus session.":"Step away, stretch, and return refreshed.";renderTimer()}
function localRecap(text){const clean=text.replace(/\s+/g," ").trim();const sentences=clean.split(/(?<=[.!?])\s+/).filter(Boolean);const actions=sentences.filter(line=>/\b(will|need to|action|todo|follow up|by\s+(monday|tuesday|wednesday|thursday|friday|tomorrow))\b/i.test(line));const decisions=sentences.filter(line=>/\b(decided|agreed|approved|choose|move forward)\b/i.test(line));return `SUMMARY\n${sentences.slice(0,2).join(" ")||clean}\n\nDECISIONS\n${decisions.length?decisions.map(item=>"- "+item).join("\n"):"- No explicit decisions detected."}\n\nACTION ITEMS\n${actions.length?actions.map(item=>"- "+item).join("\n"):"- No clear action items detected. Add owner and deadline statements for better extraction."}`}
async function generateNotes(){const input=el("notesInput").value.trim();if(!input){notify("Paste meeting notes first.");return}el("generateNotes").disabled=true;try{if(state.apiUrl){const response=await fetch(api("/api/notes"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:input})});if(!response.ok)throw new Error();const data=await response.json();el("notesResult").textContent=data.result;el("notesMode").textContent=data.mode==="ai"?"AI recap via backend":"Backend structured recap";notify("Meeting recap generated.");return}el("notesResult").textContent=localRecap(input);el("notesMode").textContent="Local structured recap";notify("Local recap generated. Connect the API for AI.")}catch(_error){el("notesResult").textContent=localRecap(input);el("notesMode").textContent="Local structured recap";notify("API unavailable; generated a local recap instead.")}finally{el("generateNotes").disabled=false}}
function renderIntegrations(){el("integrationGrid").innerHTML=INTEGRATIONS.map(item=>`<article class="integration"><div class="integration-head"><strong>${item.name}</strong><span class="state-off">Shortcut</span></div><p class="tiny">${item.detail}. Secure sync available after backend OAuth setup.</p><a class="button secondary" href="${item.href}" target="_blank" rel="noopener">Open ${item.name}</a></article>`).join("")}
function localBotReply(message){const prompt=message.toLowerCase();if(prompt.includes("room"))return"Choose a smart room from the left, then press Join room. Connect your backend URL in Settings to see other real visitors.";if(prompt.includes("note")||prompt.includes("meeting"))return"Open Meeting notes, paste your transcript, and generate a recap. AI output activates when your backend has an AI key configured.";if(prompt.includes("focus")||prompt.includes("break"))return"Start a focus block in the right panel. Completed sessions update your Wellness metrics and prompt recovery breaks.";if(prompt.includes("connect")||prompt.includes("api"))return"Open Settings and add the deployed backend URL to turn on shared presence and server-powered assistant requests.";return"I can help with rooms, meeting notes, focus sessions, or connecting your backend."}
function addBubble(containerId,text,mine){const node=document.createElement("div");node.className="bubble"+(mine?" me":"");node.textContent=text;const container=el(containerId);container.appendChild(node);container.scrollTop=container.scrollHeight}
async function sendChat(message,containerId){addBubble(containerId,message,true);try{if(state.apiUrl){const response=await fetch(api("/api/chat"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})});if(!response.ok)throw new Error();addBubble(containerId,(await response.json()).reply,false);return}}catch(_error){notify("Assistant API unavailable; using local help.")}addBubble(containerId,localBotReply(message),false)}
function bindChat(formId,inputId,containerId){el(formId).addEventListener("submit",event=>{event.preventDefault();const input=el(inputId);const message=input.value.trim();if(!message)return;input.value="";sendChat(message,containerId)})}
document.querySelectorAll(".nav button").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));document.querySelectorAll("[data-open-settings]").forEach(button=>button.addEventListener("click",()=>setView("settings")));el("joinButton").addEventListener("click",toggleJoin);el("presenceStatus").addEventListener("change",async event=>{state.me.status=event.target.value;state.me.activity=event.target.value==="focus"?"In a focus session":event.target.value==="busy"?"In a meeting":"Available";await sendPresence();renderOffice()});document.querySelectorAll(".pill").forEach(button=>button.addEventListener("click",()=>setTimerPreset(Number(button.dataset.minutes),button.dataset.kind)));el("timerToggle").addEventListener("click",()=>{state.timer.running=!state.timer.running;renderTimer()});el("timerReset").addEventListener("click",()=>{state.timer.running=false;state.timer.remaining=state.timer.total;renderTimer()});el("generateNotes").addEventListener("click",generateNotes);el("settingsForm").addEventListener("submit",async event=>{event.preventDefault();state.me.name=el("displayName").value.trim()||"You";state.apiUrl=el("apiUrl").value.trim();el("meName").textContent=state.me.name;el("meAvatar").textContent=initials(state.me.name);saveSettings();startPolling();renderOffice();notify(state.apiUrl?"Connecting to shared office...":"Saved in local-only mode.");setView("office")});bindChat("quickBotForm","quickBotInput","quickBotMessages");bindChat("fullBotForm","fullBotInput","fullBotMessages");el("displayName").value=state.me.name==="You"?"":state.me.name;el("apiUrl").value=state.apiUrl;el("meName").textContent=state.me.name;el("meAvatar").textContent=initials(state.me.name);addBubble("quickBotMessages","Welcome. I can help you navigate the office or set up your shared backend.",false);addBubble("fullBotMessages","Ask me about rooms, focus planning, meeting notes, or backend setup.",false);renderOffice();renderTimer();renderIntegrations();startPolling();state.timerHandle=setInterval(timerTick,1000);
